#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd "$(dirname "$0")/.." && pwd)
CONFIG="$ROOT_DIR/release-please-config.json"
MANIFEST="$ROOT_DIR/.release-please-manifest.json"
RELEASE_WORKFLOW="$ROOT_DIR/.github/workflows/release-please.yml"

strip_carriage_returns() {
  tr -d '\015'
}

assert_json_value() {
  expression=$1
  expected=$2
  actual=$(jq -r "$expression" "$CONFIG" | strip_carriage_returns)

  if [ "$actual" != "$expected" ]; then
    echo "Expected $expression to be $expected, got $actual." >&2
    exit 1
  fi
}

assert_manifest_semver() {
  expression=$1
  actual=$(jq -r "$expression // empty" "$MANIFEST" | strip_carriage_returns)

  if [ -z "$actual" ]; then
    echo "Expected manifest $expression to exist." >&2
    exit 1
  fi

  if ! printf '%s\n' "$actual" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z][0-9A-Za-z.-]*)?$' >/dev/null; then
    echo "Expected manifest $expression to be a semantic version, got $actual." >&2
    exit 1
  fi
}

assert_repository_path_exists() {
  path=$1

  if [ ! -e "$ROOT_DIR/$path" ]; then
    echo "Missing release-please path: $path" >&2
    exit 1
  fi
}

assert_file_contains() {
  path=$1
  expected=$2

  if ! grep -F -- "$expected" "$path" >/dev/null; then
    echo "Expected $path to contain: $expected" >&2
    exit 1
  fi
}

line_number() {
  path=$1
  text=$2

  grep -nF -- "$text" "$path" | head -n 1 | cut -d: -f 1
}

assert_file_order() {
  path=$1
  earlier=$2
  later=$3

  earlier_line=$(line_number "$path" "$earlier")
  later_line=$(line_number "$path" "$later")
  if [ -z "$earlier_line" ] || [ -z "$later_line" ] || [ "$earlier_line" -ge "$later_line" ]; then
    echo "Expected '$earlier' to appear before '$later' in $path." >&2
    exit 1
  fi
}

assert_step_contains() {
  path=$1
  step=$2
  expected=$3

  step_line=$(line_number "$path" "$step")
  if [ -z "$step_line" ] || ! awk -v start="$step_line" '
    NR < start { next }
    NR == start { in_step = 1 }
    in_step && NR > start && /^      - name: / { exit }
    in_step { print }
  ' "$path" | grep -F -- "$expected" >/dev/null; then
    echo "Expected step '$step' to contain: $expected" >&2
    exit 1
  fi
}

assert_package_path_exists() {
  package_path=$1
  path=$2

  case "$path" in
    /*)
      assert_repository_path_exists "${path#/}"
      ;;
    *)
      assert_repository_path_exists "$package_path/$path"
      ;;
  esac
}

assert_changelog_exists() {
  package_path=$1
  changelog_path=$2

  assert_package_path_exists "$package_path" "$changelog_path"
}

assert_json_value '.["pull-request-header"] | contains("unity-package")' 'true'
assert_json_value '.["pull-request-header"] | contains("uloop-project-runner")' 'true'
assert_json_value '.["pull-request-header"] | contains("`dispatcher`")' 'true'
# The dispatcher joined release-please management, so the header must not keep
# claiming that dispatcher releases are outside this release PR.
assert_json_value '.["pull-request-header"] | contains("not generated by this release PR")' 'false'

# Package roots are the release boundary: the repository root must not be a
# package, otherwise unrelated root-level changes leak into unity-package releases.
assert_json_value '.packages | keys | sort | join(",")' 'Packages/src,dispatcher,project-runner'

assert_json_value '.packages["Packages/src"].["changelog-path"]' 'CHANGELOG.md'
assert_json_value '.packages["Packages/src"].component' 'unity-package'
assert_json_value '.packages["Packages/src"].["include-component-in-tag"]' 'false'
assert_json_value '.packages["Packages/src"] | has("exclude-paths")' 'false'
assert_json_value '.packages["Packages/src"].["extra-files"] | length' '3'
assert_json_value '.packages["Packages/src"].["extra-files"][0].path' 'package.json'
assert_json_value '.packages["Packages/src"].["extra-files"][0].jsonpath' '$.version'
assert_json_value '.packages["Packages/src"].["extra-files"][1].path' 'project-runner-pin.json'
assert_json_value '.packages["Packages/src"].["extra-files"][1].jsonpath' '$.packageVersion'
assert_json_value '.packages["Packages/src"].["extra-files"][2].path' '/.uloop/project-runner-pin.json'
assert_json_value '.packages["Packages/src"].["extra-files"][2].jsonpath' '$.packageVersion'

assert_json_value '.packages["project-runner"].component' 'uloop-project-runner'
assert_json_value '.packages["project-runner"].["include-component-in-tag"]' 'true'
assert_json_value '.packages["project-runner"].["changelog-path"]' 'CHANGELOG.md'
# The release automation cmd and internal packages that used to live under cli
# moved to tools/release-automation, so there is nothing left under project-runner
# to exclude from uloop-project-runner releases.
assert_json_value '.packages["project-runner"] | has("exclude-paths")' 'false'
assert_json_value '.packages["project-runner"].["extra-files"] | length' '4'
assert_json_value '.packages["project-runner"].["extra-files"][0].path' '/common/tools/default-tools.json'
assert_json_value '.packages["project-runner"].["extra-files"][1].path' '/common/clicontract/contract.json'
assert_json_value '.packages["project-runner"].["extra-files"][2].path' '/Packages/src/project-runner-pin.json'
assert_json_value '.packages["project-runner"].["extra-files"][2].jsonpath' '$.projectRunnerVersion'
assert_json_value '.packages["project-runner"].["extra-files"][3].path' '/.uloop/project-runner-pin.json'
assert_json_value '.packages["project-runner"].["extra-files"][3].jsonpath' '$.projectRunnerVersion'

# The dispatcher tag format must stay dispatcher-v<version> to continue the
# existing tag sequence started before release-please management.
assert_json_value '.packages["dispatcher"].component' 'dispatcher'
assert_json_value '.packages["dispatcher"].["include-component-in-tag"]' 'true'
assert_json_value '.packages["dispatcher"].["include-v-in-tag"]' 'true'
assert_json_value '.packages["dispatcher"].["versioning"]' 'prerelease'
assert_json_value '.packages["dispatcher"].["prerelease-type"]' 'beta'
assert_json_value '.packages["dispatcher"].["changelog-path"]' 'CHANGELOG.md'
assert_json_value '.packages["dispatcher"] | has("exclude-paths")' 'false'
assert_json_value '.packages["dispatcher"].["extra-files"] | length' '1'
assert_json_value '.packages["dispatcher"].["extra-files"][0].path' 'dispatcher-contract.json'
assert_json_value '.packages["dispatcher"].["extra-files"][0].jsonpath' '$.dispatcherVersion'

assert_file_contains "$RELEASE_WORKFLOW" 'id: package_release_sync'
assert_file_contains "$RELEASE_WORKFLOW" "steps.package_release_sync.outputs.ready != 'false'"
assert_file_contains "$RELEASE_WORKFLOW" '  actions: write'
assert_file_contains "$RELEASE_WORKFLOW" '  checks: read'
assert_file_contains "$RELEASE_WORKFLOW" '      - name: Setup Go for package release sync'
assert_file_contains "$RELEASE_WORKFLOW" '      - name: Setup Go for release PR automation'
assert_file_contains "$RELEASE_WORKFLOW" '      - name: Dispatch release PR checks'
assert_file_contains "$RELEASE_WORKFLOW" '        working-directory: tools/release-automation'
assert_file_contains "$RELEASE_WORKFLOW" '        run: go run ./cmd/dispatch-release-please-pr-checks'
assert_step_contains "$RELEASE_WORKFLOW" '      - name: Setup Go for release PR automation' "        if: steps.target.outputs.branch == 'v3-beta' && steps.release_commit.outputs.skip != 'true' && steps.package_release_sync.outputs.ready != 'false' && steps.release.outputs.prs_created == 'true'"
assert_step_contains "$RELEASE_WORKFLOW" '      - name: Dispatch release PR checks' "        if: steps.target.outputs.branch == 'v3-beta' && steps.release_commit.outputs.skip != 'true' && steps.package_release_sync.outputs.ready != 'false' && steps.release.outputs.prs_created == 'true'"
assert_file_order "$RELEASE_WORKFLOW" '      - name: Setup Go for package release sync' 'Sync release-please package releases'
assert_file_order "$RELEASE_WORKFLOW" '      - name: Setup Go for release PR automation' '      - name: Dispatch release PR checks'

assert_manifest_semver '.["Packages/src"]'
assert_manifest_semver '.["project-runner"]'
assert_manifest_semver '.["dispatcher"]'

# The old repository-root package key must not linger after the boundary move.
# has(".") detects the key even when its value is null, which a plain
# truthiness check under jq -e would miss.
if jq -e 'has(".")' "$MANIFEST" >/dev/null 2>&1; then
  echo "Manifest must not contain the legacy '.' package key." >&2
  exit 1
fi

jq -r '.packages | to_entries[] | [.key, .value["changelog-path"]] | @tsv' "$CONFIG" |
strip_carriage_returns |
while IFS='	' read -r package_path changelog_path; do
  assert_changelog_exists "$package_path" "$changelog_path"
done

jq -r '.packages | to_entries[] | .key as $package_path | .value["extra-files"][]?.path as $extra_file_path | [$package_path, $extra_file_path] | @tsv' "$CONFIG" |
strip_carriage_returns |
while IFS='	' read -r package_path extra_file_path; do
  assert_package_path_exists "$package_path" "$extra_file_path"
done

# release-please matches exclude-paths as directory prefixes only (a commit file
# counts as excluded when it starts with "<entry>/"), so a plain-file entry can
# never match anything and silently does nothing. Require existing directories.
jq -r '.packages | to_entries[] | .value["exclude-paths"][]?' "$CONFIG" |
strip_carriage_returns |
while IFS= read -r exclude_path; do
  if [ ! -d "$ROOT_DIR/$exclude_path" ]; then
    echo "release-please exclude-paths entry must be an existing directory: $exclude_path" >&2
    exit 1
  fi
done
