#!/usr/bin/env sh

changed_cli_ts="$(git diff --cached --name-only --diff-filter=ACMR | grep -E '^Packages/src/Cli~/src/.*\.(ts|tsx)$' || true)"

if [ -n "$changed_cli_ts" ]; then
  cd Packages/src/Cli~
  npm run lint
  npx tsc --noEmit
  npx knip
fi
