#!/usr/bin/env sh

changed_cli_ts="$(git diff --cached --name-only --diff-filter=ACMR | grep -E '^cli/src/.*\.(ts|tsx)$' || true)"

if [ -n "$changed_cli_ts" ]; then
  cd cli
  npm run lint
  npx tsc --noEmit
  npx knip
fi
