package automation

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"text/template"
)

const (
	homebrewTapTokenEnvName      = "HOMEBREW_TAP_TOKEN"
	homebrewFormulaPath          = "Formula/uloop.rb"
	homebrewTapBranch            = "main"
	homebrewDarwinArm64AssetName = "uloop-dispatcher-darwin-arm64.tar.gz"
	homebrewDarwinAmd64AssetName = "uloop-dispatcher-darwin-amd64.tar.gz"
	homebrewDispatcherTagPrefix  = "dispatcher-v"
)

var homebrewDispatcherVersionPattern = regexp.MustCompile(`^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$`)

const homebrewFormulaTemplate = `# typed: false
# frozen_string_literal: true

# This file is generated by the update-homebrew-formula command in
# https://github.com/{{.Repository}} — do not edit by hand.
class Uloop < Formula
  desc "Let AI drive Unity, from Editor to Play Mode"
  homepage "https://github.com/{{.Repository}}"
  version "{{.Version}}"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/{{.Repository}}/releases/download/dispatcher-v{{.Version}}/uloop-dispatcher-darwin-arm64.tar.gz"
      sha256 "{{.SHA256Arm64}}"
    end
    on_intel do
      url "https://github.com/{{.Repository}}/releases/download/dispatcher-v{{.Version}}/uloop-dispatcher-darwin-amd64.tar.gz"
      sha256 "{{.SHA256Amd64}}"
    end
  end

  def install
    bin.install "uloop"
  end

  def caveats
    legacy_path = File.expand_path("~/.local/bin/uloop")
    return "" unless File.exist?(legacy_path)

    <<~EOS
      A curl-installed uloop exists at #{legacy_path}.
      Remove it (or fix your PATH order) so the Homebrew-managed
      binary is the one that runs:
        rm #{legacy_path}
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uloop --version")
  end
}
`

type homebrewFormulaUpdateConfig struct {
	repository string
	tag        string
	tapRepo    string
}

type homebrewFormulaUpdateDeps struct {
	runOutput func(ctx context.Context, extraEnv []string, name string, args ...string) (string, error)
}

type homebrewFormulaData struct {
	Version     string
	Repository  string
	SHA256Arm64 string
	SHA256Amd64 string
}

type homebrewTapContentResponse struct {
	SHA     string `json:"sha"`
	Content string `json:"content"`
}

type homebrewExistingFormula struct {
	present bool
	sha     string
	content string
}

// RunUpdateHomebrewFormula refreshes Formula/uloop.rb in the Homebrew tap for a dispatcher release.
func RunUpdateHomebrewFormula(ctx context.Context, stdout io.Writer, stderr io.Writer, args []string) int {
	config, err := parseHomebrewFormulaUpdateFlags(args)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}
	return runUpdateHomebrewFormulaWithDeps(ctx, stdout, stderr, config, defaultHomebrewFormulaUpdateDeps())
}

func defaultHomebrewFormulaUpdateDeps() homebrewFormulaUpdateDeps {
	return homebrewFormulaUpdateDeps{
		runOutput: runHomebrewFormulaUpdateCommandOutput,
	}
}

func parseHomebrewFormulaUpdateFlags(args []string) (homebrewFormulaUpdateConfig, error) {
	flagSet := flag.NewFlagSet("update-homebrew-formula", flag.ContinueOnError)
	repository := flagSet.String("repo", "", "GitHub repository that owns the dispatcher release")
	tag := flagSet.String("tag", "", "dispatcher release tag such as dispatcher-v3.0.0")
	tapRepo := flagSet.String("tap-repo", "", "Homebrew tap repository in owner/name form")
	err := flagSet.Parse(args)
	if err != nil {
		return homebrewFormulaUpdateConfig{}, err
	}
	if *repository == "" {
		return homebrewFormulaUpdateConfig{}, fmt.Errorf("--repo is required")
	}
	if *tag == "" {
		return homebrewFormulaUpdateConfig{}, fmt.Errorf("--tag is required")
	}
	if *tapRepo == "" {
		return homebrewFormulaUpdateConfig{}, fmt.Errorf("--tap-repo is required")
	}
	return homebrewFormulaUpdateConfig{
		repository: *repository,
		tag:        *tag,
		tapRepo:    *tapRepo,
	}, nil
}

func runUpdateHomebrewFormulaWithDeps(
	ctx context.Context,
	stdout io.Writer,
	stderr io.Writer,
	config homebrewFormulaUpdateConfig,
	deps homebrewFormulaUpdateDeps,
) int {
	// Why: releases must stay green until the tap PAT is configured; skip is intentional, not a failure.
	tapToken := strings.TrimSpace(os.Getenv(homebrewTapTokenEnvName))
	if tapToken == "" {
		writeHomebrewFormulaUpdateLine(stdout, "HOMEBREW_TAP_TOKEN is not configured; skipping Homebrew formula update.")
		return 0
	}

	version, err := dispatcherVersionFromReleaseTag(config.tag)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}

	arm64SHA256, err := downloadHomebrewAssetSHA256(ctx, deps, config.repository, config.tag, homebrewDarwinArm64AssetName)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}
	amd64SHA256, err := downloadHomebrewAssetSHA256(ctx, deps, config.repository, config.tag, homebrewDarwinAmd64AssetName)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}

	formula, err := renderHomebrewFormula(homebrewFormulaData{
		Version:     version,
		Repository:  config.repository,
		SHA256Arm64: arm64SHA256,
		SHA256Amd64: amd64SHA256,
	})
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}

	existing, err := readHomebrewTapFormula(ctx, deps, config.tapRepo, tapToken)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}
	if existing.present && existing.content == formula {
		writeHomebrewFormulaUpdateLine(stdout, fmt.Sprintf("Formula already up to date for %s; skipping.", version))
		return 0
	}

	err = writeHomebrewTapFormula(ctx, deps, config.tapRepo, tapToken, version, formula, existing)
	if err != nil {
		writeHomebrewFormulaUpdateLine(stderr, "update-homebrew-formula:", err)
		return 1
	}
	writeHomebrewFormulaUpdateLine(stdout, fmt.Sprintf("Updated Homebrew formula to %s.", version))
	return 0
}

func dispatcherVersionFromReleaseTag(tag string) (string, error) {
	if !strings.HasPrefix(tag, homebrewDispatcherTagPrefix) {
		return "", fmt.Errorf("release tag %q must start with %s", tag, homebrewDispatcherTagPrefix)
	}
	version := strings.TrimPrefix(tag, homebrewDispatcherTagPrefix)
	if !homebrewDispatcherVersionPattern.MatchString(version) {
		return "", fmt.Errorf("release tag %q has an invalid dispatcher version", tag)
	}
	return version, nil
}

func parseSha256Asset(content string, expectedAssetName string) (string, error) {
	fields := strings.Fields(content)
	if len(fields) < 2 {
		return "", fmt.Errorf("sha256 asset for %s is empty or malformed", expectedAssetName)
	}
	hash := fields[0]
	filename := fields[1]
	if len(hash) != 64 || !isHexString(hash) {
		return "", fmt.Errorf("sha256 asset for %s has an invalid hash", expectedAssetName)
	}
	if filename != expectedAssetName {
		return "", fmt.Errorf("sha256 asset filename %q does not match %q", filename, expectedAssetName)
	}
	return hash, nil
}

func isHexString(value string) bool {
	for _, char := range value {
		isDigit := char >= '0' && char <= '9'
		isLower := char >= 'a' && char <= 'f'
		isUpper := char >= 'A' && char <= 'F'
		if !isDigit && !isLower && !isUpper {
			return false
		}
	}
	return true
}

func renderHomebrewFormula(data homebrewFormulaData) (string, error) {
	parsed, err := template.New("uloop-formula").Parse(homebrewFormulaTemplate)
	if err != nil {
		return "", err
	}
	var builder strings.Builder
	err = parsed.Execute(&builder, data)
	if err != nil {
		return "", err
	}
	return builder.String(), nil
}

func downloadHomebrewAssetSHA256(
	ctx context.Context,
	deps homebrewFormulaUpdateDeps,
	repository string,
	tag string,
	assetName string,
) (string, error) {
	output, err := deps.runOutput(
		ctx,
		nil,
		"gh",
		"release",
		"download",
		tag,
		"--repo",
		repository,
		"--pattern",
		assetName+".sha256",
		"--output",
		"-",
	)
	if err != nil {
		return "", err
	}
	return parseSha256Asset(output, assetName)
}

func readHomebrewTapFormula(
	ctx context.Context,
	deps homebrewFormulaUpdateDeps,
	tapRepo string,
	tapToken string,
) (homebrewExistingFormula, error) {
	output, err := deps.runOutput(
		ctx,
		[]string{"GH_TOKEN=" + tapToken},
		"gh",
		"api",
		"repos/"+tapRepo+"/contents/"+homebrewFormulaPath+"?ref="+homebrewTapBranch,
	)
	if err != nil {
		if strings.Contains(err.Error(), "HTTP 404") {
			return homebrewExistingFormula{present: false}, nil
		}
		return homebrewExistingFormula{}, err
	}

	response := homebrewTapContentResponse{}
	err = json.Unmarshal([]byte(output), &response)
	if err != nil {
		return homebrewExistingFormula{}, fmt.Errorf("failed to parse tap formula contents: %w", err)
	}
	decoded, err := base64.StdEncoding.DecodeString(strings.ReplaceAll(response.Content, "\n", ""))
	if err != nil {
		return homebrewExistingFormula{}, fmt.Errorf("failed to decode tap formula contents: %w", err)
	}
	return homebrewExistingFormula{
		present: true,
		sha:     response.SHA,
		content: string(decoded),
	}, nil
}

func writeHomebrewTapFormula(
	ctx context.Context,
	deps homebrewFormulaUpdateDeps,
	tapRepo string,
	tapToken string,
	version string,
	formula string,
	existing homebrewExistingFormula,
) error {
	args := []string{
		"api",
		"-X",
		"PUT",
		"repos/" + tapRepo + "/contents/" + homebrewFormulaPath,
		"-f",
		"message=chore: update uloop formula to " + version,
		"-f",
		"content=" + base64.StdEncoding.EncodeToString([]byte(formula)),
		"-f",
		"branch=" + homebrewTapBranch,
	}
	if existing.present {
		args = append(args, "-f", "sha="+existing.sha)
	}
	_, err := deps.runOutput(ctx, []string{"GH_TOKEN=" + tapToken}, "gh", args...)
	return err
}

func writeHomebrewFormulaUpdateLine(writer io.Writer, values ...any) {
	// CI status output failures cannot be recovered after the command outcome is known.
	_, _ = fmt.Fprintln(writer, values...)
}

func runHomebrewFormulaUpdateCommandOutput(ctx context.Context, extraEnv []string, name string, args ...string) (string, error) {
	command := exec.CommandContext(ctx, name, args...)
	if len(extraEnv) > 0 {
		command.Env = append(os.Environ(), extraEnv...)
	}
	stdout := bytes.Buffer{}
	stderr := bytes.Buffer{}
	command.Stdout = &stdout
	command.Stderr = &stderr
	err := command.Run()
	if err != nil {
		return "", fmt.Errorf("%s %s failed: %w\n%s%s", name, strings.Join(args, " "), err, stderr.String(), stdout.String())
	}
	return stdout.String(), nil
}
