package automation

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"strings"
	"testing"
)

const (
	testHomebrewArm64SHA256 = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	testHomebrewAmd64SHA256 = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
)

// TestDispatcherVersionFromReleaseTag verifies dispatcher release tags are stripped and validated.
func TestDispatcherVersionFromReleaseTag(t *testing.T) {
	cases := []struct {
		name    string
		tag     string
		want    string
		wantErr bool
	}{
		{name: "beta tag", tag: "dispatcher-v3.0.0-beta.30", want: "3.0.0-beta.30"},
		{name: "stable tag", tag: "dispatcher-v3.1.0", want: "3.1.0"},
		{name: "missing dispatcher prefix", tag: "v3.0.0", wantErr: true},
		{name: "empty version", tag: "dispatcher-v", wantErr: true},
		{name: "path traversal version", tag: "dispatcher-v../evil", wantErr: true},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := dispatcherVersionFromReleaseTag(tc.tag)
			if tc.wantErr {
				if err == nil {
					t.Fatalf("expected error for tag %q, got version %q", tc.tag, got)
				}
				return
			}
			if err != nil {
				t.Fatalf("dispatcherVersionFromReleaseTag(%q) failed: %v", tc.tag, err)
			}
			if got != tc.want {
				t.Fatalf("dispatcherVersionFromReleaseTag(%q) = %q, want %q", tc.tag, got, tc.want)
			}
		})
	}
}

// TestParseSha256Asset verifies sha256sum-format lines are validated against the expected asset name.
func TestParseSha256Asset(t *testing.T) {
	validHash := testHomebrewArm64SHA256
	validLine := validHash + "  " + homebrewDarwinArm64AssetName + "\n"

	got, err := parseSha256Asset(validLine, homebrewDarwinArm64AssetName)
	if err != nil {
		t.Fatalf("parseSha256Asset failed: %v", err)
	}
	if got != validHash {
		t.Fatalf("hash mismatch: %q", got)
	}

	if _, err := parseSha256Asset("not-a-hash  "+homebrewDarwinArm64AssetName+"\n", homebrewDarwinArm64AssetName); err == nil {
		t.Fatal("expected error for non-hex hash")
	}
	if _, err := parseSha256Asset(validHash+"  wrong-name.tar.gz\n", homebrewDarwinArm64AssetName); err == nil {
		t.Fatal("expected error for filename mismatch")
	}
	if _, err := parseSha256Asset("", homebrewDarwinArm64AssetName); err == nil {
		t.Fatal("expected error for empty input")
	}
}

// TestRenderHomebrewFormula verifies the formula template renders the exact expected Ruby source.
func TestRenderHomebrewFormula(t *testing.T) {
	got, err := renderHomebrewFormula(homebrewFormulaData{
		Version:     "3.0.0-beta.30",
		Repository:  "hatayama/unity-cli-loop",
		SHA256Arm64: testHomebrewArm64SHA256,
		SHA256Amd64: testHomebrewAmd64SHA256,
	})
	if err != nil {
		t.Fatalf("renderHomebrewFormula failed: %v", err)
	}
	want := `# typed: false
# frozen_string_literal: true

# This file is generated by the update-homebrew-formula command in
# https://github.com/hatayama/unity-cli-loop — do not edit by hand.
class Uloop < Formula
  desc "Let AI drive Unity, from Editor to Play Mode"
  homepage "https://github.com/hatayama/unity-cli-loop"
  version "3.0.0-beta.30"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.0.0-beta.30/uloop-dispatcher-darwin-arm64.tar.gz"
      sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    end
    on_intel do
      url "https://github.com/hatayama/unity-cli-loop/releases/download/dispatcher-v3.0.0-beta.30/uloop-dispatcher-darwin-amd64.tar.gz"
      sha256 "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
    end
  end

  def install
    bin.install "uloop"
  end

  def caveats
    legacy_path = File.expand_path("~/.local/bin/uloop")
    return "" unless File.exist?(legacy_path)

    <<~EOS
      A curl-installed uloop exists at #{legacy_path}.
      Remove it (or fix your PATH order) so the Homebrew-managed
      binary is the one that runs:
        rm #{legacy_path}
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/uloop --version")
  end
}
`
	if got != want {
		t.Fatalf("formula mismatch:\n got:\n%s\nwant:\n%s", got, want)
	}
}

// TestUpdateHomebrewFormulaSkipsWithoutToken verifies an unset tap token exits 0 without calling gh.
func TestUpdateHomebrewFormulaSkipsWithoutToken(t *testing.T) {
	t.Setenv(homebrewTapTokenEnvName, "")
	calls := 0
	deps := homebrewFormulaUpdateDeps{
		runOutput: func(context.Context, []string, string, ...string) (string, error) {
			calls++
			return "", errors.New("runOutput must not be called when the tap token is unset")
		},
	}

	var stdout bytes.Buffer
	var stderr bytes.Buffer
	code := runUpdateHomebrewFormulaWithDeps(
		context.Background(),
		&stdout,
		&stderr,
		homebrewFormulaUpdateConfig{
			repository: "hatayama/unity-cli-loop",
			tag:        "dispatcher-v3.0.0-beta.30",
			tapRepo:    "hatayama/homebrew-tap",
		},
		deps,
	)

	if code != 0 {
		t.Fatalf("exit code = %d, stderr=%s", code, stderr.String())
	}
	if !strings.Contains(stdout.String(), "skipping") {
		t.Fatalf("expected skipping log, got: %s", stdout.String())
	}
	if calls != 0 {
		t.Fatalf("runOutput called %d times", calls)
	}
}

// TestUpdateHomebrewFormulaCreatesFormulaWhenAbsent verifies a missing tap formula is created without sha.
func TestUpdateHomebrewFormulaCreatesFormulaWhenAbsent(t *testing.T) {
	t.Setenv(homebrewTapTokenEnvName, "tap-token")
	formula, err := renderHomebrewFormula(homebrewFormulaData{
		Version:     "3.0.0-beta.30",
		Repository:  "hatayama/unity-cli-loop",
		SHA256Arm64: testHomebrewArm64SHA256,
		SHA256Amd64: testHomebrewAmd64SHA256,
	})
	if err != nil {
		t.Fatalf("renderHomebrewFormula failed: %v", err)
	}
	encodedFormula := base64.StdEncoding.EncodeToString([]byte(formula))

	var putArgs []string
	deps := homebrewFormulaUpdateDeps{
		runOutput: func(_ context.Context, extraEnv []string, name string, args ...string) (string, error) {
			joined := strings.Join(args, " ")
			switch {
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinArm64AssetName+".sha256"):
				return testHomebrewArm64SHA256 + "  " + homebrewDarwinArm64AssetName + "\n", nil
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinAmd64AssetName+".sha256"):
				return testHomebrewAmd64SHA256 + "  " + homebrewDarwinAmd64AssetName + "\n", nil
			case strings.Contains(joined, "repos/hatayama/homebrew-tap/contents/"+homebrewFormulaPath):
				if strings.Contains(joined, "-X PUT") {
					putArgs = append([]string{}, args...)
					return `{"content":{"sha":"new-sha"}}`, nil
				}
				if len(extraEnv) == 0 || !strings.Contains(strings.Join(extraEnv, "\n"), "GH_TOKEN=tap-token") {
					t.Fatalf("expected tap token env on contents GET, got %v", extraEnv)
				}
				return "", errors.New("gh api failed: HTTP 404 Not Found")
			default:
				return "", errors.New("unexpected command: " + name + " " + joined)
			}
		},
	}

	code := runUpdateHomebrewFormulaWithDeps(
		context.Background(),
		&bytes.Buffer{},
		&bytes.Buffer{},
		homebrewFormulaUpdateConfig{
			repository: "hatayama/unity-cli-loop",
			tag:        "dispatcher-v3.0.0-beta.30",
			tapRepo:    "hatayama/homebrew-tap",
		},
		deps,
	)
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if len(putArgs) == 0 {
		t.Fatal("expected PUT call")
	}
	joinedPut := strings.Join(putArgs, " ")
	if !strings.Contains(joinedPut, "content="+encodedFormula) && !containsFlagValue(putArgs, "content", encodedFormula) {
		t.Fatalf("PUT missing base64 formula content: %v", putArgs)
	}
	if containsFlagName(putArgs, "sha") {
		t.Fatalf("create path must not pass sha: %v", putArgs)
	}
}

// TestUpdateHomebrewFormulaUpdatesExistingFormula verifies an existing formula PUT includes the blob sha.
func TestUpdateHomebrewFormulaUpdatesExistingFormula(t *testing.T) {
	t.Setenv(homebrewTapTokenEnvName, "tap-token")
	oldContent := "# old formula\n"
	payload, err := json.Marshal(map[string]string{
		"sha":     "existing-sha",
		"content": base64.StdEncoding.EncodeToString([]byte(oldContent)),
	})
	if err != nil {
		t.Fatalf("marshal content response: %v", err)
	}

	var putArgs []string
	deps := homebrewFormulaUpdateDeps{
		runOutput: func(_ context.Context, _ []string, name string, args ...string) (string, error) {
			joined := strings.Join(args, " ")
			switch {
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinArm64AssetName+".sha256"):
				return testHomebrewArm64SHA256 + "  " + homebrewDarwinArm64AssetName + "\n", nil
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinAmd64AssetName+".sha256"):
				return testHomebrewAmd64SHA256 + "  " + homebrewDarwinAmd64AssetName + "\n", nil
			case strings.Contains(joined, "repos/hatayama/homebrew-tap/contents/"+homebrewFormulaPath):
				if strings.Contains(joined, "-X PUT") {
					putArgs = append([]string{}, args...)
					return `{"content":{"sha":"new-sha"}}`, nil
				}
				return string(payload), nil
			default:
				return "", errors.New("unexpected command: " + name + " " + joined)
			}
		},
	}

	code := runUpdateHomebrewFormulaWithDeps(
		context.Background(),
		&bytes.Buffer{},
		&bytes.Buffer{},
		homebrewFormulaUpdateConfig{
			repository: "hatayama/unity-cli-loop",
			tag:        "dispatcher-v3.0.0-beta.30",
			tapRepo:    "hatayama/homebrew-tap",
		},
		deps,
	)
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if !containsFlagValue(putArgs, "sha", "existing-sha") {
		t.Fatalf("PUT missing existing sha: %v", putArgs)
	}
}

// TestUpdateHomebrewFormulaSkipsWhenContentIdentical verifies an unchanged formula does not PUT.
func TestUpdateHomebrewFormulaSkipsWhenContentIdentical(t *testing.T) {
	t.Setenv(homebrewTapTokenEnvName, "tap-token")
	formula, err := renderHomebrewFormula(homebrewFormulaData{
		Version:     "3.0.0-beta.30",
		Repository:  "hatayama/unity-cli-loop",
		SHA256Arm64: testHomebrewArm64SHA256,
		SHA256Amd64: testHomebrewAmd64SHA256,
	})
	if err != nil {
		t.Fatalf("renderHomebrewFormula failed: %v", err)
	}
	payload, err := json.Marshal(map[string]string{
		"sha":     "existing-sha",
		"content": base64.StdEncoding.EncodeToString([]byte(formula)),
	})
	if err != nil {
		t.Fatalf("marshal content response: %v", err)
	}

	putCalls := 0
	deps := homebrewFormulaUpdateDeps{
		runOutput: func(_ context.Context, _ []string, name string, args ...string) (string, error) {
			joined := strings.Join(args, " ")
			switch {
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinArm64AssetName+".sha256"):
				return testHomebrewArm64SHA256 + "  " + homebrewDarwinArm64AssetName + "\n", nil
			case strings.Contains(joined, "release download") && strings.Contains(joined, homebrewDarwinAmd64AssetName+".sha256"):
				return testHomebrewAmd64SHA256 + "  " + homebrewDarwinAmd64AssetName + "\n", nil
			case strings.Contains(joined, "repos/hatayama/homebrew-tap/contents/"+homebrewFormulaPath):
				if strings.Contains(joined, "-X PUT") {
					putCalls++
					return "", errors.New("PUT must not run when content is identical")
				}
				return string(payload), nil
			default:
				return "", errors.New("unexpected command: " + name + " " + joined)
			}
		},
	}

	var stdout bytes.Buffer
	code := runUpdateHomebrewFormulaWithDeps(
		context.Background(),
		&stdout,
		&bytes.Buffer{},
		homebrewFormulaUpdateConfig{
			repository: "hatayama/unity-cli-loop",
			tag:        "dispatcher-v3.0.0-beta.30",
			tapRepo:    "hatayama/homebrew-tap",
		},
		deps,
	)
	if code != 0 {
		t.Fatalf("exit code = %d", code)
	}
	if putCalls != 0 {
		t.Fatalf("PUT called %d times", putCalls)
	}
	if !strings.Contains(stdout.String(), "already up to date") {
		t.Fatalf("expected up-to-date log, got: %s", stdout.String())
	}
}

func containsFlagName(args []string, name string) bool {
	flag := "-f"
	for index := 0; index < len(args); index++ {
		if args[index] != flag {
			continue
		}
		if index+1 >= len(args) {
			return false
		}
		if strings.HasPrefix(args[index+1], name+"=") {
			return true
		}
	}
	return false
}

func containsFlagValue(args []string, name string, value string) bool {
	expected := name + "=" + value
	for index := 0; index < len(args); index++ {
		if args[index] == "-f" && index+1 < len(args) && args[index+1] == expected {
			return true
		}
		if args[index] == expected {
			return true
		}
	}
	return false
}
